name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Frontend
      run: npm run build

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "hpp-vaalikone"
        heroku_email: "pitkanentuukka@gmail.com"
        buildpack: "heroku/nodejs"
        run_prebuild: "true"
        github_url: "https://github.com/pitkanentuukka/voting-front"
        app_dir: "backend/public"
